version: "3"

services:
  ingestion:
    image: ingestion:latest
    build:
      context: ./ingestion
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    env_file:
      - ingestion/app.env
    links:
      - mariadb
#  app:
#    image: app:latest
#    build:
#      context: ./app
#      dockerfile: Dockerfile
#    restart: always
#    depends_on:
#      - mariadb
#    ports:
#    - "5050:5050"
#    env_file:
#      - app/app.env
#    links:
#      - mariadb
  mariadb:
    image: mariadb:10.7
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql/data
      - mariadb_logs:/var/lib/mysql/logs
      - mariadb_conf:/var/docker/mariadb/conf
    env_file:
      - mariadb.env
volumes:
  mariadb_data:
  mariadb_logs:
  mariadb_conf: